### ISSUE TITLE
Finish documentation examples

### ISSUE THREAD

**Issue by gadomski** [gadomski/stac-rs#22]
We're still missing a lot, especially around [`Stac`](https://docs.rs/stac/latest/stac/struct.Stac.html) and the render methods.

**Comment by pkopparla** [comment]
A bit unrelated maybe, but in [README.md](https://github.com/gadomski/stac-rs/blob/main/README.md)
`
cargo run --examples copy data/catalog.json tmp
`
doesn't work, but 
`
cargo run --example copy data/catalog.json tmp
` does.

**Comment by gadomski** [comment]
https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#documenting-components provides the recommended structure for component documentation.

**Comment by pkopparla** [comment]
A question, the `render` method seems to have a documentation page here already: https://docs.rs/stac/latest/stac/layout/struct.Layout.html#method.render

What is to be added to complete documentation examples here?

**Comment by pkopparla** [comment]
Thanks!
