### ISSUE TITLE
Add jsonschema validation

### ISSUE THREAD

**Issue by gadomski** [gadomski/stac-rs#27]
The current ecosystem options for jsonschema validation are:
- https://crates.io/crates/jsonschema
- https://crates.io/crates/valico

These seem more mature than the last time I looked, so I'm hopeful. This should probably be behind a (non-default?) feature.

One thing I'd like to see is storing the released schema documents in the library itself, rather than forcing network access for validation.

**Comment by duckontheweb** [comment]
@gadomski I had success implementing validation using `jsonschema` in [my own Rust-STAC experiment](https://github.com/duckontheweb/rustac/blob/main/rustac-validate/src/lib.rs). I would be interested in helping implement it here if you're interested. 

> One thing I'd like to see is storing the released schema documents in the library itself, rather than forcing network access for validation.

I like this idea, but one consequence of having these stored in the library is that we would have to publish a new release for every update to an extension version, which could get cumbersome. Maybe we could store schemas in the library and then fall back to fetching them over the network if we don't have the schema stored locally?

**Comment by gadomski** [comment]
Yeah this would be cool, if you wanted to take a crack at it I'd be all for it!

> one consequence of having these stored in the library is that we would have to publish a new release for every update to an extension version, which could get cumbersome. Maybe we could store schemas in the library and then fall back to fetching them over the network if we don't have the schema stored locally?

Sure, but isn't this how pystac works currently as well? The fallback strategy makes sense to deal with "unrecognized" versions, though.

This relates to an issue I have with jsonschema more generally, namely the lack of semver support wrt schema id-via-url. I'm thinking more and more that there's significant value to add by providing a non-jsonschema validation engine as an additional feature.
